### ISSUE TITLE
EL CENTINELA TE BORRA TODOS LOS ITEMS

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#140]
SI NO LE PONES LA CLAVE, EL CENTINELA TE BORRA TODOS LOS ITEMS Y TE MANDA A LA CARCEL.

NO TIENE POR QUE BORRAR ITEMS, ARREGLAR ESTE PROBLEMA URGENTE!
![Screen Shot 2019-05-09 at 10 58 09 PM](https://user-images.githubusercontent.com/5874806/57448677-16912e00-72ae-11e9-87c7-eccdfe1a4752.png)

**Comment by jopiortiz** [comment]
Ya arreglaste esto. Cierro.
