### ISSUE TITLE
El comando /mod no funciona en personajes con nombres que tienen un espacio espacio

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#141]
El comando /mod no funciona en personajes con nombres que tienen un espacio espacio ejemplo

`/mod JUAN PEREZ oro 2000`

**Comment by jopiortiz** [comment]
Creo que sí funcionan. Pero al escribir el comando tenés que reemplazar los espacios con el signo `+`

Por ejemplo, `/MOD JUAN+PEREZ oro 2000`

**Comment by RecoX** [comment]
Dale hoy lo pruebo si puedo, ojala funcione

**Comment by RecoX** [comment]
funciona correctamente, cierro esto.
