### ISSUE TITLE
Guia completa para los Admins/GMs

### ISSUE THREAD

**Issue by neoranger** [ao-libre/ao-server#154]
Estaba chequeando la nueva versión del server (me funciona genial ahora) y mi idea es tener un server propio pero hay un inconveniente, como Admin del servidor no conozco todos los comandos que los Admins pueden usar. Busqué en la Wiki o en la web y no hay apartado para los GMs o Admins para que puedan utilizar el servidor y sacar su potencial al máximo.

**Comment by RecoX** [comment]
Estan aca:
https://www.reddit.com/r/argentumonlineoficial/comments/9fpd7r/comandos_diosessemidiosesconsejeros/

y aca:
http://wiki.argentumonline.org/indexfc81.html?seccion=controlesycomandos#ver

Esta ultima habria que actualizarla, o sacar todos los comandos de ahi y poner un link a reddit, lo que sea mas comodo.

Se podria crear tambien un comando `/comandos` o `/help` en el juego para que nos de un link con todos los comandos.
