### ISSUE TITLE
Server_bkp.ini no queda igual

### ISSUE THREAD

**Issue by neoranger** [ao-libre/ao-server#159]
Cuando se levanta un server y al querer apagarse con la opción "con backup", el archivo .ini que genera no queda igual que la configuración que se está usando en ese momento.

El archivo de backup:
- No guarda los admins
- El tag release es viejo
- Vuelve los dados a su original (si es que se cambian)
- Setea el server solo para GMs
- Setea a 10 los segundos de desconexión (seteo por defecto)
- No guarda el apartado de conexión a la API
- Agrega una linea en blanco de por medio por cada linea escrita en el archivo

**Comment by RecoX** [comment]
Estas seguro que se genera un archivo bkp.ini al hacer world save? estoy leyendo el codigo y no encuentro nada de eso.

**Comment by neoranger** [comment]
No se de donde salió ese archivo. corrijo, no genera nada.
