### ISSUE TITLE
Fallo en el comando GM /MiembrosClan

### ISSUE THREAD

**Issue by Bassinger** [ao-libre/ao-server#21]
![14-09-2018 17-19-47](https://user-images.githubusercontent.com/31661806/45559315-71b77180-b842-11e8-8ef8-d5c96511b978.jpg)

Como os muestro en el ScreenCapture, utilizo el comando /MiembroClan para comprobar la lista de cada clanes, cuando lo utilizo, me dice que el clan no existe. Como ven en la imagen, si que existe.

**Comment by cucsijuan** [comment]
probe el comando y a mi me esta funcionando, solo note que no estaba la carpeta guilds y el inf correspondiente
