### ISSUE TITLE
Experiencia y Oro

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-server#27]
Hola, a pesar de estar aplicados en el server.ini no me toma la multiplicación de EXP y ORO en el CLIENTE, muy bueno el proyecto y lo estoy utilizando en mi KVM, cuenten conmigo para seguir probando cosas.

**Comment by RecoX** [comment]
Muchas gracias por reportar el fallo
@cucsijuan alguna idea ?

**Comment by RecoX** [comment]
Acabo de hacer un test de este bug y efectivamente funciona bien.

Cierro el ticket
