### ISSUE TITLE
Quests no funcionan

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#288]
**Que hiciste para que ocurriera? // What did you do?**
Pones un npcs de quest, le haces doble click escribis /quest y te hecha del juego.

**Que esperabas que pase? // What did you expect to happen?**
Que funcione bien el modulo de quests.

**Comment by Wyr0X** [comment]
Fixeado con #331

**Comment by RecoX** [comment]
Reportan el el discord que esto sigue pasando y no fue totalmente arreglado.

Reabro para seguir investigando

**Comment by abusiv0** [comment]
Fixeado hace ya unos días.
