### ISSUE TITLE
 Arreglar/Completar Clan Praetoriano

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#3]
En esta version del servidor:
http://www.gs-zone.org/temas/argentum-online-13-0-con-directx8.36676/

El archivo praetorians.bas tiene mas de 2000 lineas de codigo de diferencia.

Off topic:
En este repositorio encontre funciones como:
HandleCentinelReport
HandleSpellInfo

que en nuestro repositorio no estan, capaz son de utilidad..

**Comment by RecoX** [comment]
Clan Pretoriano:

Al ir al mapa 163 no hay nadie del clan praetoriano
No deja usar comando acc 900 por que arroja mensaje que dice que es clan praetoriano el npc
el comando /crearclanpraetoriano no existe pero esta en el mensaje de eeror de acc 900

**Comment by juandpr** [comment]
Vamos a actualizar el mensaje para que pegue con el comando que se debe usar que es /CREARPRETORIANOS

**Comment by RecoX** [comment]
En este codigo, hay cosas que podrian ser utiles en Pretorians.bas
https://www.gs-zone.org/temas/argentum-online-13-0-con-directx8.36676/

**Comment by jopiortiz** [comment]
Ya estan implementados los pretorianos y los centinelas.
