### ISSUE TITLE
Error en Server Remoto

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-server#30]
Estimados, lo estuve probando via localhost y no pasó naranja, subí el server a un hosting y el juego se congela (en partes, la parte de los menu's funciona ok) no se muestra info al clickear, no toma comandos tipo /SALIR se pierde conexión pero el PJ queda conectado...quizas me faltó acomodar algo en el visual.

**Comment by RecoX** [comment]
Es muy extraño esto ya que el servidor que nosotros tenemos montado en un server dedicado funciona bien sin esos problemas.

**Comment by cucsijuan** [comment]
@plusin podes tirar ping al menos? es raro como dice recox lo tenemos subido al un host y funciona perfecto, deberias probar sin tocar nada, bajarlo de github y ejecutar el exe, ni siquiera desde el visual basic, y si es posible hacer ping con el cliente hacelo y decime cuanto tenes.
