### ISSUE TITLE
Error tras update ao-server

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-server#31]
Estimados, vi que modificaron el ao-server y lo descargué, al momento de querer iniciar cliente obtengo:

Error '429' en tiempo de ejecución:
El componente ActiveX no puede crear el objeto.

**Bonus Track para no ser tan pesado con los bugs**

IniciarDesdeBackup=0 viene por default, deberían ponerlo en 1 asi cualquier cosa que modifique un GM ingame quedá guardada, sino levanta sin backup tengo entendido.

**Comment by RecoX** [comment]
No puedo reproducirlo lamentablemente, podrias poner mas detalles de que sistema operativo estas usando por ejemplo? tenes instalado direct x 8 ?? librerias?
----------
Con respecto a la configuracion del `server.ini` la idea es que sea customizada por los usuarios pero para entender ese archivo se necesita crear esta tarea:
https://github.com/ao-libre/ao-server/issues/33

**Comment by plusin** [comment]
1) Estaba usando otro puerto distinto al indicado por server.ini
2) Me faltaba algun ocx.
