### ISSUE TITLE
Crear lista explicando propiedades en carpeta DAT

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#33]
Se necesita una lista explicando cada archivo que se encuentra en la carpeta [Dat](https://github.com/ao-libre/ao-server/blob/master/Dat) en formato Markdown para incluir en readme.md en el repositorio del servidor

Este es el formato deseado:
 
 - [Motd.ini](https://github.com/ao-libre/ao-server/blob/master/Dat/Motd.ini)
En este archivo se pueden escribir textos que apareceran a los usuarios al conectarse al servidor.

Codigo ejemplo a seguir:
```
- [Motd.ini](https://github.com/ao-libre/ao-server/blob/master/Dat/Motd.ini)
En este archivo se pueden escribir textos que apareceran a los usuarios al conectarse al servidor.
```

**Comment by jopiortiz** [comment]
Hecho! [https://github.com/ao-libre/ao-server/commit/9808b5053cbad5782b717356147b7945f816a426](Commit)
