### ISSUE TITLE
Sumario explicando propiedades server.ini

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#34]
Se necesita una lista explicando cada propiedad que se encuentra en [Server.ini](https://github.com/ao-libre/ao-server/blob/master/Server.ini) en formato Markdown para incluir en readme.md en el repositorio del servidor

Este es el formato deseado:
 
 - *ExpMulti*: Multiplicador de experiencia.

Codigo ejemplo a seguir:
```
 - *ExpMulti*: Multiplicador de experiencia.
```

**Comment by RecoX** [comment]
See comments addressed in this issue:

https://github.com/ao-libre/ao-server/issues/47

**Comment by juandpr** [comment]
Shall we edit the readme.md in this repository?

**Comment by RecoX** [comment]
For now yes, I think is the easiest and ordered way to find it out today.

**Comment by plusin** [comment]
[INIT]
- *CrcSubKey*: A borrar
- *StartPort*: Puerto que utiliza el servidor
- *Hide*: Oculta o muestra el servidor en la lista de servidores
- *AllowMultiLogins*: Permite iniciar más de un cliente en una PC o no
- *IdleLimit*: Limite de inactividad para ser desconectado del servidor (minutos)
- *Version*: Versión del cliente aceptada por el servidor
- *IniciarDesdeBackup*: Permite cargar el backup del servidor o no (relacionado a cambios en los 

mapas)
- *ClientsCommandsQueue*: A borrar
- *CleanInterval*: Tiempo de ejecución en minutos de la limpieza de items en el piso del servidor
- *PuedeCrearPersonajes*: Habilita o deshabilita la posibilidad de crear nuevos personajes

- *ExpMulti*: Multiplicador de experiencia
- *OroMulti*: Multipllicador de oro
- *OficioMulti*: Multiplicador de oficio
- *MinDados*: Valor minimo en la suerte con los dados
- *MaxDados*: Valor maximo en la suerte con los dados

- *ContadorAntiPiquete*: Valor en minutos en que el servidor encarcela a un usuario.
- *MinutosCarcelPiquete*: Valor en minutos que dura la pena en la carcel de un usuario.

- *ServerSoloGMs*: Habilita o deshabilita el servidor solo para GameMasters
- *Testing*: Habilita o deshabilita el servidor para betatesters (?)
- *Encriptar*: Habilita o deshabilita el encriptamiento del servidor (?)

- *CamaraLenta*: Habilita o deshabilita el modo camara lenta del servidor (lag excesivo)

- *ArmaduraImperial1*: Numero de obj que identifica esta vestimenta faccionaria
- *TunicaMagoImperial*: Numero de obj que identifica esta vestimenta faccionaria
- *TunicaMagoImperialEnanos*: Numero de obj que identifica esta vestimenta faccionaria
- *ArmaduraImperial2*: Numero de obj que identifica esta vestimenta faccionaria
- *ArmaduraImperial3*: Numero de obj que identifica esta vestimenta faccionaria

- *ArmaduraCaos1*: Numero de obj que identifica esta vestimenta faccionaria
- *TunicaMagoCaos*: Numero de obj que identifica esta vestimenta faccionaria
- *TunicaMagoCaosEnanos*: Numero de obj que identifica esta vestimenta faccionaria
- *ArmaduraCaos2*: Numero de obj que identifica esta vestimenta faccionaria
- *ArmaduraCaos3*: Numero de obj que identifica esta vestimenta faccionaria

- *VestimentaImperialHumano*: Numero de obj que identifica esta vestimenta faccionaria
- *VestimentaImperialEnano*: Numero de obj que identifica esta vestimenta faccionaria
- *TunicaConspicuaHumano*: Numero de obj que identifica esta vestimenta faccionaria
- *TunicaConspicuaEnano*: Numero de obj que identifica esta vestimenta faccionaria
- *ArmaduraNobilisimaHumano*: Numero de obj que identifica esta vestimenta faccionaria
- *ArmaduraNobilisimaEnano*: Numero de obj que identifica esta vestimenta faccionaria
- *ArmaduraGranSacerdote*: Numero de obj que identifica esta vestimenta faccionaria

- *VestimentaLegionHumano*: Numero de obj que identifica esta vestimenta faccionaria
- *VestimentaLegionEnano*: Numero de obj que identifica esta vestimenta faccionaria
- *TunicaLobregaHumano*: Numero de obj que identifica esta vestimenta faccionaria
- *TunicaLobregaEnano*: Numero de obj que identifica esta vestimenta faccionaria
- *TunicaEgregiaHumano*: Numero de obj que identifica esta vestimenta faccionaria
- *TunicaEgregiaEnano*: Numero de obj que identifica esta vestimenta faccionaria
- *SacerdoteDemoniaco*: Numero de obj que identifica esta vestimenta faccionaria

- *MapaPretoriano*: Establece el mapa donde se activan los npc's pretorianos

- *MaxUsers*: Establece el numero máximo de conexiones al servidor


- *StartPos*: Establece la posición inicial de un PJ (mapa - pos x - pos y)
- *Record*: Muestra el record de conexiones al servidor

- *Admines*: Establece la cantidad de Administradores del servidor
- *Dioses*: Establece la cantidad de Dioses del servidor
- *SemiDioses*: Establece la cantidad de SemiDioses del servidor
- *Consejeros*: Establece la cantidad de Consejeros del servidor
- *RolesMasters*: Establece la cantidad de RolesMasters del servidor

[Admines]
- *Admin1*: Establece el nombre del PJ que va a ser Administrador

[Dioses]
- *Dios1*: Establece el nombre del PJ que va a ser Dios

[SemiDioses]
- *Semidios1*: Establece el nombre del PJ que va a ser SemiDios

[Consejeros]
- *Consejero1*: Establece el nombre del PJ que va a ser Consejero

[RolesMasters]
- *RM1*: Establece el nombre del PJ que va a ser RolesMasters

; Argentum Online - Server Side Library
[AOSSLib]
;;todos los directorios asumen ser subs de App.Path;;
;directorio donde escribira el log
logdir=logs
;directorio charfiles usado por CAutoDeleteUsers
chardir=charfile


[INTERVALOS]
{cuanto mas chico el número, más velocidad para realizar esa acción}
- *SanaIntervaloSinDescansar*: intervalo para sanar sin descansar
- *StaminaIntervaloSinDescansar*: intervalo de stamina sin descansar
- *SanaIntervaloDescansar*: intervalo de sanar descansando
- *StaminaIntervaloDescansar*: intervalo de stamina descansando
- *IntervaloSed*: intervalo de sed
- *IntervaloHambre*: intervalo de hambre
- *IntervaloVeneno*: intervalo de veneno (duración del hechizo)
- *IntervaloParalizado*: intervalo de paralizado (duración del hechizo)
- *IntervaloInvisible*: intervalo de invisible (duración del hechizo)
- *IntervaloOculto*: intervalo de oculto (capacidad de ocultarse)
- *IntervaloFrio*: intervalo de frío (cuando baja la energía por frío)
- *IntervaloWAVFX*: intervalo de sonidos fx
- *IntervaloMover*: intervalo de moverse
- *IntervaloLanzaHechizo*: intervalo para lanzar un hechizo
- *IntervaloNpcAI*: intervalo de la inteligencia artificial de los NPCS
- *IntervaloNpcPuedeAtacar*: intervalo de ataque de los NPCS
- *IntervaloTrabajo*: intervalo de trabajo (talar, pescar, minar)
- *IntervaloUserPuedeAtacar*: intervalo de ataque de los usuarios
- *IntervaloWS*: intervalo de worldsave 'Cantidad de minutos
- *IntervaloInvocacion*: intervalo de invocación de criaturas (duración del hechizo)
- *IntervaloPerdidaStaminaLluvia*: intervalo de perder stamina con la lluvia
- *IntervaloParaConexion*: intervalo para conectarse
- *IntervaloTimerExec*: intervalo de timer
- *IntervaloCerrarConexion*: intervalo de cerrar conexión 'Cantidad de segundos
- *IntervaloUserPuedeUsar*: intervalo de usar objetos
- *IntervaloFlechasCazadores*: inetervalo de usar flechas
- *IntervaloAutoReiniciar*: intervalo para autoreiniciar el servidor '-1 para deshabilitar
- *IntervaloMagiaGolpe*: intervalo de golpe con hechizo de magia
- *IntervaloGolpeMagia*: intervalo de golpe + hechizo de magia *dudoso
- *IntervaloGolpeUsar*: intervalo de golpe
- *IntervaloGuardarUsuarios*: intervalo de guardar charfiles


[MD5Hush]
- *Activado*: activda md5 hush
- *MD5Aceptados*: cantidad de codigos md5 aceptados
- *VerArchivosCriticos*: activa o desactiva la visualización de archivos criticos

'cliente normal
Md5Aceptado1=6c27fd12ae7e76247d1a3fb278321240

'cliente AlphaBlending
Md5Aceptado2=2c5c6253c3fb6c81617f315e0f7d589f

**Comment by RecoX** [comment]
Genio, ahora mismo voy a agregar esto al `readme.md` :)

**Comment by RecoX** [comment]
#34 closed

Added the information in reddit, added link in readme.md
