### ISSUE TITLE
Cambiar la forma en que está hecha el packet resend y cómo se busca el UserIndex a partir del número de socket

### ISSUE THREAD

**Issue by imASas** [ao-libre/ao-server#37]
Propongo que se implemente esto, es mucho mas optimo que el timer packetResend.

Link donde esta implementado: https://www.4shared.com/rar/qPGW85knee/Argentum_Online_135.html

**Comment by juandpr** [comment]
Hola @imASas, no conozco mucho el protocolo. Pero me podes comentar en que mejoraria eso y exactamente donde se realiza eso que decis del packet resend? Gracias!

**Comment by RecoX** [comment]
Esto que nombran se encuentra aqui para mas info.
https://www.gs-zone.org/temas/argentum-online-13-5.98461/#post-833659
