### ISSUE TITLE
Rectificar ataque de Gran dragón dorado o cambiarlo de mapa

### ISSUE THREAD

**Issue by CuidadosoBander** [ao-libre/ao-server#378]
El dragón no ataca.
Posible causa: Su ataque es mágico y está en un mapa no mágico.

**Comment by ReyarB** [comment]
En que mapa esta?

**Comment by RecoX** [comment]
Dragon Rojo - Dungeon Dragon
Dragon Dorado - Dungeon Infierno (??)
Dragon Negro - Dungeon Tierra.
