### ISSUE TITLE
Hacer que los npcs de magia vendan todos los hechizos disponibles

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#380]
Hacer que los npcs de magia vendan todos los hechizos disponibles ya que hay muchos que no los venden y la gente quiere comprar hechizos como elemental de agua y no estan.

**Comment by cemercuri** [comment]
Seguros de esto? La venta de hechizos no va variando dependiendo la ciudad intencionalmente?
En caso de que confirmen, lo hago.

**Comment by RecoX** [comment]
Esto quedo viejo y no se va a hacer para mover a la gente a todos lados.
