### ISSUE TITLE
Los pjs a veces tienen 9999999 de exp por error y no pueden subir mas niveles

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#409]
Los pjs a veces tienen 9999999 de exp por error y no pueden subir mas niveles

[STATS]
BANCO=63150000
ELU=130933556
ELV=47
EXP=99999999
GLD=1115320
MAXAGU=100
MAXHAM=100
MAXHIT=111
MAXHP=411
MAXMAN=878
MAXSTA=750
MINAGU=30
MINHAM=60
MINHIT=111
MINHP=411
MINMAN=866
MINSTA=750
SKILLPTSLIBRES=6

Tengo un presentimiento que es por que la propiedad EXP es Double y ELU Long

**Comment by Wyr0X** [comment]
Esto no lo solucionó? PR #428

**Comment by RecoX** [comment]
> 
> 
> Esto no lo solucionó? PR #428

Puede ser ahora cierro mi PR, pense q no se habia trabajado como estaba abierto :)
