### ISSUE TITLE
Crear parametro en server.ini para activar/desactivar tirar dados

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#42]
Tarea relacionada
https://github.com/ao-libre/ao-cliente/issues/79

Se dara a elegir la posibilidad de tirar dados para la asignacion de atributos.

Se requiere crear un parametro en `server.ini` llamado `dados` para activar o desactivar los dados.

Se requiere crear un parametro en `server.ini` llamado `atributosInicioCantidad` para poder personalizar la cantidad de puntos de skills disponibles a  asignar al crear un personaje.

En caso de que `dados` esta en modo desactivado, utilizar el valor asignado en `atributosInicioCantidad` para asignar atributos

**Comment by nujhiga** [comment]
Me encargo de ésta.

**Comment by juandpr** [comment]
Alguna novedad @nujhiga ? Como tenes pensado hacerlo?

**Comment by RecoX** [comment]
Lamentablemente @nujhiga no puede colaborar ahora en el proyecto.
Esta tarea esta libre.

**Comment by juandpr** [comment]
Bueno, la tomo yo.
Mi propuesta, un parametro en el server.ini que diga Dados=1/0 (Con un nombre mas explicativo).
Si esta habilitado, todo sigue como esta, caso contrario, tira los dados 18.
Capaz la solucion ideal seria que se oculten en la interface cliente pero es un bardo, ya que hay que crear otra interface

**Comment by RecoX** [comment]
Dale creo que un nombre mas explicativo como `dadosActivados`  booleano seria ideal

Con respecto a la interface, podriamos hacer una solucion simple como tener dos imagenes una con los dados y otra sin. 
El diseño no es una parte importante por ahora ya que la idea con esta tarea https://github.com/ao-libre/ao-cliente/issues/80 cambiaria este problema. Con tan solo una imagen con un cuadrado negro ocultando los dados seria suficiente por ahora creo yo.

Con respecto a la cantidad de atributos en el parametro`atributosInicioCantidad` si no es dificil de implementar seria bueno ya que se le da una posibilidad a los servidores de crear server denominados como "fruta" de manera facil donde todos pueden empezar con atributos realmente altos para "agitar" out of the box

**Comment by juandpr** [comment]
Si por ahi se va mucho ya del objetivo inicial, yo creo que deberiamos cerrar con tareas mas pequenas, en ultima instancia podriamos crear dos parametros. `minDados` y `maxDados`, y si quieren "desactivarlos" que pongan 18 y 18 en ambos.

**Comment by RecoX** [comment]
Perfecto, vamos con eso.

**Comment by cucsijuan** [comment]
Me gusta la idea de max min, va co la idea de hacer el server mas configurable sin tener que tocar código.

**Comment by juandpr** [comment]
https://github.com/ao-libre/ao-server/pull/50

**Comment by juandpr** [comment]
Merged
