### ISSUE TITLE
Hay algunos instrumentos que no suenan

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#451]
![image](https://user-images.githubusercontent.com/5874806/79281048-21186680-7f06-11ea-8990-b44defd71695.png)

**Comment by cemercuri** [comment]
Actualmente el tambor suena como tambor, el laúd como laúd y la flauta (común) suena como flauta.
Las flautas mágica y élfica no tienen sonido pqe son equipables y su función no es hacer música digamos. Estando invi podrías deschavarte con el sound por ejemplo.
**Issue para cerrar.**

**Comment by RecoX** [comment]
> 
> 
> Actualmente el tambor suena como tambor, el laúd como laúd y la flauta (común) suena como flauta.
> Las flautas mágica y élfica no tienen sonido pqe son equipables y su función no es hacer música digamos. Estando invi podrías deschavarte con el sound por ejemplo.
> **Issue para cerrar.**

Concuerdo, solo hay que cambiar esto
https://github.com/ao-libre/ao-cliente/issues/749
