### ISSUE TITLE
Error en actualizar con botón "server.ini" ExpMulti y OroMulti

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-server#47]
Comento que descubrí lo que asumo es un bug con el cual sucede que al terminar de modificar la multiplicación de exp y de oro (no probé si con trabajar pasa lo mismo) y luego querer actualizar desde el server con el boton "server.ini" dicha configuración no es aplicada en el momento, también comento que al reiniciar cliente y servidor multiplica correctamente.

**Comment by juandpr** [comment]
El problema radica en que una vez que recargas el server.ini, se recargan los parametros de oro y exp pero los NPCs ya creados mantienen su experiencia y oro. Te diria que es practicamente imposible lograr esto, ya que si por ejemplo, un usuario esta matando un NPC y le quedan 100 de vida y vos actualizas la exp, como actuas en ese caso?

Basicamente, lo ideal es reiniciar el server luego de actualizar exp y oro.

**Comment by RecoX** [comment]
Perfecto, yo tampoco sabia eso hay que hacer una aclaracion con esos parametros en esta tarea

https://github.com/ao-libre/ao-server/issues/34

@juandpr queda a tu criterio cerrarla o ver que pasa aca
