### ISSUE TITLE
Creacion de Pj: Debe tirar los dados para continuar

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#5]
Al crear un pj a veces el menu arroja el siguiente error: Debe tirar los dados para continuar aunque se tiren los dados, sigue apareciendo el mismo error

**Comment by cucsijuan** [comment]
I cant reproduce this bug, any suggestion?

**Comment by RecoX** [comment]
I can reproduce it, its random.

<img width="1440" alt="screen shot 2018-09-29 at 10 14 46 am" src="https://user-images.githubusercontent.com/5874806/46240380-a870b880-c3fa-11e8-8187-c3b7391753de.png">
