### ISSUE TITLE
Usuarios pueden atacar GameMasters

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-server#56]
Les comento que acabo de probar atacar a un GM y lo pude hacer sin problemas, no se debería poder.

![errorpegarlegm](https://user-images.githubusercontent.com/7727108/48278566-ab64bd00-e42c-11e8-8052-7cba68f1fb93.jpg)

**Comment by plusin** [comment]
Lo probé en otro mapa y aparece la leyenda "El ser es demasiado poderoso" supongo que en el mapa del screenshot se permite pegarle a GMS's o.O

**Comment by RecoX** [comment]
Podemos confirmar que fue por alguna validacion de mapa esto ? o efectivamente es un error ?

**Comment by Juanmz** [comment]
En 13.0 se puede atacar gms en trigger 6. La onda es sacarlo porque si haces eventos te empiezan a molestar o agregar un comando para que el gm pueda activarlo y desactivarlo.
