### ISSUE TITLE
Mimetizar funciona mal en agua

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#570]
![image](https://user-images.githubusercontent.com/5874806/86523918-b43eb800-bec7-11ea-929d-f386c99955f0.png)

Leer el chat

**Comment by CuicuiEB** [comment]
Fixed. 
Commit: https://github.com/ao-libre/ao-server/commit/880aeb40d9ea6a5d58f05566c13e389952e25cb7
