### ISSUE TITLE
Mantener cuenta al cerrar sesion

### ISSUE THREAD

**Issue by juandpr** [ao-libre/ao-server#58]
Como usuario, estaria bueno que al tipear /SALIR pueda mantener mi cuenta abierta para cambiar de personaje.
Se podria implementar un checkbox tambien que diga "mantenerme logeado".

**Comment by RecoX** [comment]
o que aparezca un popup con 2 botones

Salir / Cambiar Personaje

**Comment by RecoX** [comment]
@abusiv0 @jopiortiz Habria que implementar esto tambien con el comando `/salir` o no?

ya que tenemos el desarrollo hecho
