### ISSUE TITLE
Los mensajes del foro se borran, que no se borren nunca!

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#593]
Los mensajes del foro se borran, que no se borren nunca!

**Comment by CuicuiEB** [comment]
Y cómo querés que quede guardado el foro?
Se me ocurre que cada vez que tenga que limpiar un foro, renombre el foro viejo con algo como no sé.. Month(Date) & "-" & year(Date) & ".for"

**Comment by RecoX** [comment]
> 
> 
> Y cómo querés que quede guardado el foro?
> Se me ocurre que cada vez que tenga que limpiar un foro, renombre el foro viejo con algo como no sé.. Month(Date) & "-" & year(Date) & ".for"

sinceramente no se como funciona el foro ahora, pero se podria guardar todo en un .ini y listo.
