### ISSUE TITLE
Seguridad: Comparar MD5 Hash del cliente antes de iniciar conexion

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-server#6]
Debemos crear un sistema de proteccion para que un cliente modificado no se pueda conectar al servidor, la solucion que se me ocurre es verificar el MD5 Hash del cliente con el aceptado en el servidor, en caso que no sea el mismo rechazar la conexion.

**Comment by jormot** [comment]
My two cents: lo ideal es usar CRC para esto.

**Comment by jopiortiz** [comment]
MD5 fue eliminado ya.
