### ISSUE TITLE
Crear pretorianos deberia funcionar solo como GM

### ISSUE THREAD

**Issue by juandpr** [ao-libre/ao-server#60]
Siendo un usuario comun se puede usar el comando /CREARPRETORIANOS

**Comment by RecoX** [comment]
que jerarquia de GM?

**Comment by juandpr** [comment]
Admin o Dios en mi opinion

**Comment by RecoX** [comment]
Dios en adelante creo que tiene q ser

**Comment by jopiortiz** [comment]
Ya esta hecho este.
