### ISSUE TITLE
Lluvia cierra el cliente

### ISSUE THREAD

**Issue by juandpr** [ao-libre/ao-server#61]
Al momento en que empieza a llover, el cliente se cierra. A veces tira un runtime error y a veces no, solo se cierra. Intentamos debugear con VB6 pero tambien se nos cierra, haciendo imposible el saber en que linea se rompe.
Para reproducir:
1) Logearse como GM
2) Ejecutar el comando /LLUVIA

Probado con cliente y server `master` y `16_Database_Integration`

**Comment by RecoX** [comment]
https://github.com/ao-libre/ao-cliente/issues/107

**Comment by RecoX** [comment]
No lo puedo reproducir, a mi me funciona bien windows 7 64 bits.
