### ISSUE TITLE
HappyHour error

### ISSUE THREAD

**Issue by CuicuiEB** [ao-libre/ao-server#615]
El HappyHour dice que a partir de ese momento los NPC darían un 200% de experiencia, pero por cómo está codeado eso va a pasar con los futuros NPC que spawneen.
Habría que actualizar la experiencia de los NPC activos
![image](https://user-images.githubusercontent.com/9663888/87209124-30ca0000-c2e7-11ea-93bf-b7809d8e077c.png)

**Comment by Wyr0X** [comment]
Esto se arregló con #690, alguien me puede confirmar si ya anda bien?
