### ISSUE TITLE
AppCrash Server.exe

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-server#63]
Después de uno o dos días el server.exe se cierra solo, esto comenzó a ocurrir en el ultimo update desde que se implemento el instalador con juego, server y world editor.

**Detalle del error cuando la app crashea:**

> Problem signature:
>   Problem Event Name:	APPCRASH
>   Application Name:	server.exe
>   Application Version:	0.13.0.0
>   Application Timestamp:	5c1c8104
>   Fault Module Name:	KERNELBASE.dll
>   Fault Module Version:	6.1.7601.24231
>   Fault Module Timestamp:	5b6db2d4
>   Exception Code:	c0000005
>   Exception Offset:	00024079
>   OS Version:	6.1.7601.2.1.0.400.8
>   Locale ID:	1033
>   Additional Information 1:	59d2
>   Additional Information 2:	59d28f4851ee3e61e3aa57edc696ac9e
>   Additional Information 3:	4941
>   Additional Information 4:	49412c9cadeee270197f45131b8323af

**Logs de la carpeta server:**
errores.log:

> 12/26/2018 2:22:00 PM Error en GmCommands. Error: 28 - Out of stack space. Paquete: 39

--

HackAttemps.log:
`12/26/2018 2:22:00 PM dsadsa IP:168.181.177.65 trató de hackear los skills.`

--

**Comment by MateoMiccino** [comment]
Este error se ocasiona cuando el `Sub HandleIncomingData` se llama tantas veces a si mismo, que la pila no puede seguir stackeando funciones.

La forma de arreglarlo, es hacer que el `Sub HandleIncomingData` devuelva `TRUE` o `FALSE` en caso de que haya o no mas datos, y luego sea iterado con un `WHILE` por quien lo llame

**Comment by RecoX** [comment]
Solucionado con este PR
https://github.com/ao-libre/ao-server/pull/122

**Comment by RecoX** [comment]
Se re-abre ya que el PR tiene errores que hay que corregir.
