### ISSUE TITLE
Faltan los gobernadores de varias ciudades

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-server#778]
**Que sistema operativo usas ? // What operating system and version?** W10

**Que hiciste para que ocurriera? // What did you do?** Recorri las ciudades

**Que esperabas que pase? // What did you expect to happen?** Que haya gobernadores para declararse ciudadano de ese lugar en el caso de que quieras cambiar la que elegis cuando creas el personaje.

**Que fue lo que paso? // What actually happened?** Solo lo vi en ulla al gobernador.

**Comment by RecoX** [comment]
Agregue los gobernadores de las nuevas ciudades, habria que ponerlos en los mapas

@ErikAolibre si podes ver que todos esten en donde corresponde seria ideal.
