### ISSUE TITLE
Revisar Server.ini

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-server#779]
**Que sistema operativo usas ? // What operating system and version?** W10

**Que hiciste para que ocurriera? // What did you do?** Quise correr el server como viene actualizado

**Que esperabas que pase? // What did you expect to happen?** Que el server arranque bien con el mismo valor del cliente.

**Que fue lo que paso? // What actually happened?** El server tiene 0.13.52 y el client 0.13.51

**Comment by RecoX** [comment]
Esto no es necesariamiente asi. las versiones de server y cliente no tienen por que ser parejas, a veces no hace falta actualziar ambos
![image](https://user-images.githubusercontent.com/5874806/91272488-e7b70800-e7cf-11ea-8fa1-86ed09f66082.png)

En la pagina podes ver las ultimas versiones disponibles, aunque con el Launcher siempre vas a bajar lo ultimo
