### ISSUE TITLE
Error al compilar servidor.

### ISSUE THREAD

**Issue by facundopirex** [ao-libre/ao-server#80]
Error: no se ha definido el tipo por el usuario
en esta linea en Admin.bas Public EstadisticasWeb As clsEstadisticasIPC

Pero, estuve leyendo y en el modulo general si esta el Set EstadisticasWeb = New clsEstadisticasIPC.

Por eso no entiendo el por que.
(Quizas se ejecute primero Public EstadisticasWeb As clsEstadisticasIPC antes de Set EstadisticasWeb = New clsEstadisticasIPC?)

**Comment by RecoX** [comment]
Hola @facundopirex gracias por escribir

Te comento, este error es un problema con GIT, el problema es que el EOL que maneja VB6 es CLRF y al bajar el repositorio el archivo .vbp a veces viene con el EOL como UNIX, al pasar esto el proyecto se abre mal y hay dependencias que faltan. 

Hice algunos intentos de arreglarlo con el archivo .gitattributes pero no tuve exito, se que es por este lado la solucion pero aun no logro hacerlo, este es un problema que realmente estoy muy interesado personalmente en arreglarlo ya que a muchas personas les pasa, en cuanto tenga un tiempo espero poder sentarme otra ves y poder solucionarlo definitivamente.

En la descripcion del proyecto en la seccion FAQ hay una pequeña guia de como solucionarlo, pero te lo dejo aqui

Error - Al abrir el proyecto en Visual Basic 6 no puede cargar todas las dependencias:

Este es un error comun que les suele pasar a varias personas, esto es debido que el EOL del archivo esta corrupto. Visual Basic 6 lee el .vbp en CLRF, hay varias formas de solucionarlo:

Opcion a: Con Notepad++ cambiar el EOL del archivo a CLRF

Opcion b: Abrir un editor de texto y reemplazar todos los '\n' por '\r\n'

Desde ya disculpa las molestias y cualquier cosa avisanos si pudiste asi puedo cerrar este ticket.

PD: Hacete un Pull o bajate el proyecto nuevamente como hiciste antes ya que acabo de hacer unas modificaciones hace 5 minutos en el codigo y las necesitas para que funcione bien.

**Comment by RecoX** [comment]
@facundopirex acabo de hacer nuevos cambios al gitattributes del server, por favor podras volver a bajarlo y confirmar que te funciona?

gracias.

**Comment by facundopirex** [comment]
Apenas vuelva a mi casa lo pruebo!
Pd: No sabes qué pasó con la wiki Dev de ao?

**Comment by RecoX** [comment]
En el readme del proyecto esta el link:
https://dao.fandom.com/es/wiki/Wiki_Desarrollo_Argentum_Online

**Comment by jopiortiz** [comment]
Esa Wiki sigue andando?

**Comment by RecoX** [comment]
@jopiortiz es lo mas avanzado que hay en cuanto a saber como funcioona el AO

Despues tenemos nuestra propia wiki para poner documentacion en por ejemplo como crear un release:
https://github.com/ao-libre/ao-cliente/wiki/How-to-create-and-publish-Releases%3F

**Comment by facundopirex** [comment]
Al parecer está descontinuada.

**Comment by Derillo** [comment]
Testeado>ok> gitatributes, las Ñ ahora son Ñ.
Error>Al compilar> Runtime Error9' Subscript Out of range> getByte = data(CurrentPos)
